detect_box.py 추가 및 findDot.py 수정
Box-size/box.size-algorithm pull request #14
Opened 2023-07-25 20:50 UTC by ssigner

## Summary

yolo-v8 폴더에 yolo V8 파이썬 실행 코드 추가 및 findDot 식 수정

## Description

추후 yolo-v8에서 파이썬 코드를 통해 얻은 box.xyxy 변수를 findDot.py로 전달 필요
현재 findDot.py에는 crops와 결과물을 저장하지 않고 yolo만 실행해서 box.xyxy 변수를 얻어 상자의 꼭지점 좌표를 원본 이미지의 박스 좌표로 수정하는 상태 -> 즉 실행시간 더 오래걸림
findDot.py 식은 비례식 부분이 잘못되어 수정
현재 box9.png로 구동 시 실제값에 가까운 근사값 얻을 수 있음

2023-07-26 10:37 UTC, jagaldol requested changes

2023-07-26 10:37 UTC, jagaldol commented on findDot/findDot.py
> +    plt.show()
plt 같은 디버깅 용 확인 코드는 함수내에서 처리하지 말고 main코드로 옮겨주세요

외부에서 함수 이용하려 할 시 불필요한 plt창이 뜨며 멈추게 됩니다.

2023-07-26 10:37 UTC, jagaldol commented on yolo-v8/detect_box.py
> +print(box.xyxy)
위에 adjust_points랑 내용이 겹치는데 이 파일에서 함수로 만들고 폴더를 패키지화(`__init__.py` 생성)해서
findDot에서 호출해서 써도 좋을 거같아요.

근데 findDot에서 이걸 다시 호출하는 거 자체가 맞는 흐름이 아니여서 꼭 필요한 일은 아닙니다.

2023-07-26 10:37 UTC, jagaldol commented on findDot/findDot.py
> +    box = boxes[0]
애초에 파이프라인 자체가 predict한 다음에 nuki 타고 findDot 타는 거라 애매하네요 처음에 predict하고 box를 가지고 있다가 findDot 의 함수들 호출할때 같이 보내는 식으로 가야할 거 같은데 box 정보는 파라미터로 주입 받아야 될거 같아요

2023-07-29 05:14 UTC, ssigner commented on findDot/findDot.py
> +    box = boxes[0]
그래서 파일을 하나로 만들던지 해야 더 효율적일거 같아요

2023-07-29 05:50 UTC, jagaldol approved these changes
승인할게요

2023-07-29 05:50 UTC, merged